apiVersion: v1
kind: Service
metadata:
  name: astral-key
  namespace: {{ .Release.Namespace }}
  labels:
    app: astral-key
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: astral-key
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
