apiVersion: v1
kind: ConfigMap
metadata:
  name: casdoor-config
  namespace: auth
  labels:
    app: casdoor
    app.kubernetes.io/managed-by: easykubenix
data:
  app.conf.template: |
    appname = casdoor
    httpport = 8000
    runmode = prod
    copyrequestbody = true
    driverName = postgres
    dataSourceName = user=casdoor host=casdoor-postgres.auth.svc.cluster.local port=5432 sslmode=disable dbname=casdoor
    [PASSWORD] tableNamePrefix = showSql = false redisEndpoint = defaultStorageProvider = isCloudIntranet = false authState = "casdoor"
    verificationCodeTimeout = 10 initScore = 0 logPostOnly = true isUsernameLowered = false origin = https://auth.lan staticBaseUrl = "https://auth.lan" isDemoMode = false batchSize = 100 showGithubCorner = false defaultLanguage = "en" defaultApplication = "app-built-in" maxItemsForFlatMenu = 7 enableGzip = true initDataNewOnly = false initDataFile = "./init_data.json"