apiVersion: v1
kind: ServiceAccount
metadata:
  name: password-generator
  namespace: auth
  labels:
    app: casdoor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: password-generator
  namespace: auth
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["casdoor-postgres-secret"]
  verbs: ["get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: password-generator
  namespace: auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: password-generator
subjects:
- kind: ServiceAccount
  name: password-generator
  namespace: auth