apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: casdoor-tls
  namespace: auth
spec:
  secretName: casdoor-tls-secret
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - auth.lan
  - casdoor.auth.lan
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth